const DEFAULT_MASS_TYPES = [
  {
    name: 'Sunday Mass',
    default_time: '7:15 AM',
    description: 'Regular Sunday Mass',
    is_special_event: false,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
  },
  {
    name: 'Christmas Mass',
    default_time: '',
    description: 'Christmas Celebration with Carols',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
    has_carols: true,
  },
  {
    name: 'New Year Mass',
    default_time: '11:15 PM',
    description: 'New Year Thanksgiving Mass',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
    has_thanksgiving: true,
  },
  {
    name: 'Palm Sunday',
    default_time: '7:30 AM',
    description: 'Palm Sunday Mass with Gospel Narration',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
    has_gospel_narration: true,
    has_mc_reader: true,
  },
  {
    name: 'Maundy Thursday',
    default_time: '5:30 PM',
    description: 'Maundy Thursday with 12 Apostles',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
    has_mc_reader: true,
    has_apostles: true,
  },
  {
    name: 'Good Friday',
    default_time: '5:30 PM',
    description: 'Good Friday with Morning Adoration and Gospel Narration',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
    has_gospel_narration: true,
    has_mc_reader: true,
    has_morning_adoration: true,
  },
  {
    name: 'Easter Vigil',
    default_time: '11:15 PM',
    description: 'Easter Vigil Mass with Three Readings',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'third_reading', 'prayer_of_faithful'],
    has_mc_reader: true,
    has_third_reading: true,
  },
  {
    name: 'All Souls Day',
    default_time: '7:15 AM',
    description: 'All Souls Day - Remembrance of Departed Souls',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
    has_departed_souls_reader: true,
  },
  {
    name: 'Independence Day Mass',
    default_time: '7:15 AM',
    description: 'Independence Day Special Mass',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
  },
  {
    name: 'Pongal Mass',
    default_time: '7:15 AM',
    description: 'Pongal Festival Mass',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
  },
  {
    name: 'St. Cecilia Feast',
    default_time: '7:15 AM',
    description: 'Feast of St. Cecilia - Patron Saint of Musicians',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
  },
  {
    name: 'Christmas Morning Mass',
    default_time: '7:15 AM',
    description: 'Christmas Day Morning Mass',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
  },
  {
    name: 'New Year Morning Mass',
    default_time: '7:15 AM',
    description: 'New Year Day Morning Mass',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
  },
  {
    name: 'Easter Morning Mass',
    default_time: '7:15 AM',
    description: 'Easter Sunday Morning Mass',
    is_special_event: true,
    required_roles: ['introduction', 'first_reading', 'second_reading', 'prayer_of_faithful'],
  },
];

const DEFAULT_COMMUNITY_ROLES = [
  { name: 'Liturgy Coordinator', category: 'liturgy', description: 'Overall liturgy coordination' },
  { name: 'Liturgy Member', category: 'liturgy', description: 'Liturgy team member' },
  { name: 'Executive Member', category: 'executive', description: 'Executive committee member' },
  { name: 'Choir Coordinator', category: 'choir', description: 'Choir incharge' },
  { name: 'Choir Member', category: 'choir', description: 'Choir team member' },
  { name: 'Catechism Coordinator', category: 'catechism', description: 'Catechism incharge' },
  { name: 'Catechism Teacher', category: 'catechism', description: 'Catechism teacher' },
  { name: 'Volunteer Coordinator', category: 'volunteers', description: 'Volunteers incharge' },
  { name: 'Volunteer', category: 'volunteers', description: 'Community volunteer' },
];

module.exports = { DEFAULT_MASS_TYPES, DEFAULT_COMMUNITY_ROLES };
